### ISSUE TITLE
regarding to policies and reward functions 

### ISSUE THREAD

**Issue by zyzhang1130** [tigerneil/awesome-deep-rl#4]
Hi,
May I ask how do you define more than one policy and reward function concurrently in a multi-agent setting?
Thank you.

**Comment by tigerneil** [comment]
You asked a great question. 

To simplify problems, we should get the policy or reward functions of some type or within the same function family (like Distributional RL). But it is possible to consider a combination or an interpolation of functions of various types, though it is very hard because you need to guarantee the convergence of the solution. 

Or you can reduce the problem to the source of rewards: there is a paper by Christian R. Shelton: [paper](https://papers.nips.cc/paper/1831-balancing-multiple-sources-of-reward-in-reinforcement-learning.pdf)

**Comment by tigerneil** [comment]
and I think the citations can give you many ideas.

**Comment by zyzhang1130** [comment]
thank you for the reference! I shall definitely take a look!
